version: "3"

services:
  api:
    build: .
    container_name: backend-pipedrivebling
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    networks:
      - integration

  mongo:
    image: mongo
    container_name: mongodb-pipedrivebling
    ports:
      - "27017:27017"
    networks:
      - integration

networks:
  integration:
    driver: bridge
